version: '3'
services:
  library-manegement:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=Library
    ports:
      - "3307:3306"
  library-manegement-docker :
    image: library-manegement-docker
    ports:
      - "8082:3030"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://library-manegement:3306/Library?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "build/generated/sources/annotationProcessor/java/main"
      dockerfile: "DockerFile"
    depends_on:
      - library-manegement