server:
  port: 3030
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:5306/Library
#    url:  jdbc:mysql://library-management:5306/Library
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
#  flyway:
#    enabled: false
#  liquibase:
#    enabled: true
#    change-log: classpath:/liquibase/changelog-master.yaml
twilio:
  account_sid: ACa14b3aba2cff43667e4f92f7e64319d3
  auth_token: 0c2d2cdae54773fb167519fb58b2aa5d
  trial_number: +19123784027
